server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: /
  api_rules:
    url_prefix: /api/oar/v1
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en
  languages:
    - en
    - de
    - fr
    - it
  cors: true
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  pretty_print: true
  limits:
    default_items: 10
    max_items: 100

logging:
  level: DEBUG

metadata:
  identification:
    title: Swiss Geospatial Data - minimal PoC
    description: Minimal OGC API Records PoC
    keywords:
      - geospatial
      - ogc
      - switzerland
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://www.swisstopo.admin.ch
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: swisstopo PoC
    url: https://www.swisstopo.admin.ch
  contact:
    name: swisstopo
    role: pointOfContact

resources:
  swissgeo-catalogue-os:
    type: collection
    title: SWISSGEO Catalog (OpenSearch)
    description: Swiss geodata catalog backed by OpenSearch
    keywords: [switzerland, geodata, catalog, swisstopo, opensearch]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        data: ${OPENSEARCH_URL:-http://localhost:9200}/swissgeo-catalog
        resource_id: swissgeo-catalogue-os
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it

  swissgeo-distributions-os:
    type: collection
    title: SWISSGEO Distributions (OpenSearch)
    description: Swiss geodata distributions backed by OpenSearch
    keywords: [switzerland, geodata, distributions, swisstopo, opensearch]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        resource_id: swissgeo-distribution-os
        data: ${OPENSEARCH_URL:-http://localhost:9200}/swissgeo-distributions
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it

  geoadmin-services-os:
    type: collection
    title: GeoAdmin Services (OpenSearch)
    description: GeoAdmin services backed by OpenSearch
    keywords: [switzerland, geodata, services, geoadmin, opensearch]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        resource_id: geoadmin-services-os
        data: ${OPENSEARCH_URL:-http://localhost:9200}/geoadmin-services
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it
