server:
  bind:
    host: 0.0.0.0
    port: 8080
  url: ${PYGEOAPI_HOSTNAME:-http://localhost:8080}${API_PREFIX:-/api/oar/rc1}
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  language: en
  languages:
    - en
    - de
    - fr
    - it
  cors: true
  map:
    url: https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.pixelkarte-farbe/default/current/3857/{z}/{x}/{y}.jpeg
    attribution: '&copy; <a href="https://www.swisstopo.admin.ch">swisstopo</a>'
  pretty_print: true
  limits:
    default_items: 10
    max_items: 100

logging:
  level: DEBUG

metadata:
  identification:
    title: SWISSGEO OGC API Records
    description:
      de: SWISSGEO OGC API Records Katalog für Metadaten und Links.
      en: SWISSGEO OGC API Records catalogue for metadata and links.
      fr: Catalogue SWISSGEO OGC API Records pour les métadonnées et les liens.
      it: Catalogo SWISSGEO OGC API Records per metadati e link.
    keywords:
      - geospatial
      - ogc
      - switzerland
    terms_of_service: https://www.geo.admin.ch/de/allgemeine-nutzungsbedingungen-bgdi/
    url: https://www.swisstopo.admin.ch
  license:
    name:
      en: swisstopo OGD Terms of Use
      de: swisstopo OGD Nutzungsbedingungen
      fr: Conditions d'utilisation OGD swisstopo
      it: Condizioni d'uso OGD swisstopo
    url:
      en: https://www.swisstopo.admin.ch/en/terms-of-use-free-geodata-and-geoservices
      de: https://www.swisstopo.admin.ch/de/nutzungsbedingungen-kostenlose-geodaten-und-geodienste
      fr: https://www.swisstopo.admin.ch/fr/conditions-utilisation-geodonnees-et-geoservices-gratuit
      it: https://www.swisstopo.admin.ch/it/condizioni-utilizzo-geodati-e-geoservizi-gratuiti
  provider:
    name: Bundesamt für Landestopografie swisstopo
    url: https://www.swisstopo.admin.ch
  contact:
    name: KOGIS – Koordination, Geoinformation und Services
    url: https://www.geo.admin.ch
    address: Seftigenstrasse 264
    city: Wabern
    postalcode: "3084"
    country: Switzerland
    phone: +41 58 469 01 11
    email: info@geo.admin.ch
    role: pointOfContact

resources:
  swissgeo-catalog:
    type: collection
    title: SWISSGEO Catalog
    description: Swiss geodata catalog
    keywords: [switzerland, geodata, catalog, swisstopo]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        data: ${OPENSEARCH_URL:-http://localhost:9200}/swissgeo-catalog
        resource_id: swissgeo-catalog
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it

  swissgeo-distributions:
    type: collection
    title: SWISSGEO Distributions
    description: Swiss geodata distributions
    keywords: [switzerland, geodata, distributions, swisstopo]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        resource_id: swissgeo-distributions
        data: ${OPENSEARCH_URL:-http://localhost:9200}/swissgeo-distributions
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it

  geoadmin-services:
    type: collection
    title: GeoAdmin Services
    description: GeoAdmin services
    keywords: [switzerland, geodata, services, geoadmin]
    links:
      - type: text/html
        rel: canonical
        title: swisstopo
        href: https://www.swisstopo.admin.ch
        hreflang: en
    extents:
      spatial:
        bbox: [5.9, 45.8, 10.5, 47.9]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - type: record
        name: swissgeo_provider.SwissGeoProvider
        resource_id: geoadmin-services
        data: ${OPENSEARCH_URL:-http://localhost:9200}/geoadmin-services
        aws4auth: ${OPENSEARCH_AWS4AUTH:-false}
        id_field: externalId
        time_field: recordCreated
        title_field: title
        languages:
          - en
          - de
          - fr
          - it
